/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proy1.view;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Consumo;
import model.Persona;
import model.Preguntas;
import proy1.view.panelDatosPersonales;
import proy1.view.panelPreguntas;
import proy1.view.panelResultados;

/**
 *
 * @author SynM3
 */

public class Formulario extends javax.swing.JFrame {

    private int pantallaActual = 0; // 0: Datos Personales, 1: Preguntas, 2: Resultados
private Persona persona;
private Consumo consumo;
private Preguntas preguntas;

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        
        panelDatosPersonales pDatPer = new panelDatosPersonales();
        pDatPer.setSize(790, 390);
        pDatPer.setLocation(0, 0);
        
        content.removeAll();
        content.add(pDatPer, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    private void ShowPanel(JPanel p)
    {
        p.setSize(790, 390);
        p.setLocation(0, 0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnModulo1 = new javax.swing.JButton();
        btnModulo2 = new javax.swing.JButton();
        btnModulo3 = new javax.swing.JButton();
        btnIngresoRapido = new javax.swing.JButton();
        btnDatosPersonales = new javax.swing.JButton();
        btnPreguntas = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));

        btnModulo1.setBackground(new java.awt.Color(153, 255, 153));
        btnModulo1.setForeground(new java.awt.Color(0, 0, 0));
        btnModulo1.setText("Módulo de monitore de consumo de agua");

        btnModulo2.setBackground(new java.awt.Color(153, 255, 153));
        btnModulo2.setForeground(new java.awt.Color(0, 0, 0));
        btnModulo2.setText("Módulo de sugerencia para conservación del agua");

        btnModulo3.setBackground(new java.awt.Color(153, 255, 153));
        btnModulo3.setForeground(new java.awt.Color(0, 0, 0));
        btnModulo3.setText("Módulo de reportes y estadística de agua");

        btnIngresoRapido.setBackground(new java.awt.Color(153, 255, 153));
        btnIngresoRapido.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresoRapido.setText("Ingreso rápido");

        btnDatosPersonales.setBackground(new java.awt.Color(153, 255, 204));
        btnDatosPersonales.setForeground(new java.awt.Color(0, 0, 0));
        btnDatosPersonales.setText("1. Datos perosnaes");
        btnDatosPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosPersonalesActionPerformed(evt);
            }
        });

        btnPreguntas.setBackground(new java.awt.Color(153, 255, 204));
        btnPreguntas.setForeground(new java.awt.Color(0, 0, 0));
        btnPreguntas.setText("2. Preguntas");
        btnPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntasActionPerformed(evt);
            }
        });

        btnResultados.setBackground(new java.awt.Color(153, 255, 204));
        btnResultados.setForeground(new java.awt.Color(0, 0, 0));
        btnResultados.setText("3. Resultados");
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnModulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIngresoRapido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnModulo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIngresoRapido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(790, 390));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        btnInicio.setBackground(new java.awt.Color(204, 255, 204));
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(204, 255, 204));
        btnAtras.setForeground(new java.awt.Color(0, 0, 0));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(204, 255, 204));
        btnSiguiente.setForeground(new java.awt.Color(0, 0, 0));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosPersonalesActionPerformed
        panelDatosPersonales pDatPer = new panelDatosPersonales();
        ShowPanel(pDatPer);
    }//GEN-LAST:event_btnDatosPersonalesActionPerformed

    private void btnPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntasActionPerformed
        panelPreguntas pPreg = new panelPreguntas();
        ShowPanel(pPreg);
    }//GEN-LAST:event_btnPreguntasActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        panelResultados pRes = new panelResultados();
        ShowPanel(pRes);
    }//GEN-LAST:event_btnResultadosActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

        if (pantallaActual == 0) {
            // Vuelve a la pantalla de Datos Personales
            content.removeAll();
            content.add(new panelDatosPersonales());
            content.revalidate();
            content.repaint();
        } else if (pantallaActual == 1) {
            // Muestra una notificación que "si vuelvo mi progreso se perdera"
            int respuesta = JOptionPane.showConfirmDialog(null, "Si vuelvo, mi progreso se perderá. ¿Desea continuar?", "Advertencia", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                // Vuelve a la pantalla de Datos Personales
                pantallaActual = 0;
                content.removeAll();
                content.add(new panelDatosPersonales());
                content.revalidate();
                content.repaint();
            }
        } else if (pantallaActual == 2) {
            // Muestra una notificación que "si desea continuar, perdera su progreso"
            int respuesta = JOptionPane.showConfirmDialog(null, "Si desea continuar, perderá su progreso. ¿Desea continuar?", "Advertencia", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                // Vuelve a la pantalla de Datos Personales
                pantallaActual = 0;
                content.removeAll();
                content.add(new panelDatosPersonales());
                content.revalidate();
                content.repaint();
            }
        }
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        if (pantallaActual == 0) {
            // Muestra un mensaje que "no hay una opcion anterior"
            JOptionPane.showMessageDialog(null, "No hay una opción anterior");
        } else if (pantallaActual == 1) {
            // Muestra una notificación que "si vuelvo mi progreso se perdera"
            int respuesta = JOptionPane.showConfirmDialog(null, "Si vuelvo, mi progreso se perderá. ¿Desea continuar?", "Advertencia", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                // Vuelve a la pantalla de Datos Personales
                pantallaActual = 0;
                content.removeAll();
                content.add(new panelDatosPersonales());
                content.revalidate();
                content.repaint();
            }
        } else if (pantallaActual == 2) {
            // Muestra una notificación que "si desea continuar, perdera su progreso"
            int respuesta = JOptionPane.showConfirmDialog(null, "Si desea continuar, perderá su progreso. ¿Desea continuar?", "Advertencia", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                // Vuelve a la pantalla de Datos Personales
                pantallaActual = 0;
                content.removeAll();
                content.add(new panelDatosPersonales());
                content.revalidate();
                content.repaint();
            }
        }
    }//GEN-LAST:event_btnAtrasActionPerformed


    
    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
       
        if (pantallaActual == 0) {
    panelDatosPersonales pp = (panelDatosPersonales) content.getComponent(0);
    Persona personaTemp = pp.getPersona();
    if (personaTemp.getNombre().isEmpty() || personaTemp.getApellido().isEmpty() || 
        personaTemp.getEdad().isEmpty() || personaTemp.getDireccion().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese todos los datos");
    } else {
        // Pasa a la pantalla de Preguntas
        persona = personaTemp; // Usamos el objeto ya creado
        content.removeAll();
        content.add(new panelPreguntas());
        content.revalidate();
        content.repaint();
        pantallaActual = 1;
    }
} 
        else if (pantallaActual == 1) {
    panelPreguntas pp = (panelPreguntas) content.getComponent(0);
    
    try {
        // Primero validamos si está vacío
        if (pp.getConsumo().equals(pp)) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el consumo", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salimos sin continuar
        }
        
        // Luego intentamos convertir y obtener el consumo
        consumo = pp.getConsumo(); // Esto puede lanzar NumberFormatException
        preguntas = pp.getPreguntas();
        
        // Cambiamos de panel
        content.removeAll();
        content.add(new panelResultados(persona, consumo));
        content.revalidate();
        content.repaint();
        pantallaActual = 2;
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Valor inválido", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
        else if (pantallaActual == 2) {
    // No hace nada
}
    
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Formulario().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnDatosPersonales;
    private javax.swing.JButton btnIngresoRapido;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnModulo1;
    private javax.swing.JButton btnModulo2;
    private javax.swing.JButton btnModulo3;
    private javax.swing.JButton btnPreguntas;
    private javax.swing.JButton btnResultados;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JPanel content;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
